Update code to follow code convention
motivemetrics/google-ads-data pull request #4
Opened 2022-09-27 19:40 UTC by puerile22

_**Related items**_

- [[Ticket](link)](https://motivemetrics.atlassian.net/browse/RD-242?atlOrigin=eyJpIjoiMjY2MDkzN2NmNDUyNGYwOWFhNTZmY2MwZGFlMTAzZjciLCJwIjoiaiJ9)

_**Problem**_

Problem.
Google ads data repo is not following new code convention.

_**Solution**_

Update code to follow new code convention.

_**Other changes**_

-None

_**Testing**_

- No testing are done.

_**Code quality**_

- how did you verified code quality?
  - ran linters (sublimelinter flake8)

_**What can be broken**_

- Google-ads-data package could be broken.

_**Readme Updates**_

- Are there any updates that should be made to the readme?
  For example: Is there anything that you did manually to get this code working?
  - no

###### As always keep in mind that "you are not the code", we are reviewing the code solely here.

2022-09-29 17:08 UTC, mkarbouski submitted a review, later dismissed
Again nice job!

2022-09-30 12:21 UTC, rsen-motivemetrics requested changes

2022-09-30 12:22 UTC, rsen-motivemetrics commented on google_ads_data/account_utils.py
>      if account is None or "data" not in account or "customerId" not in account["data"]:
But I see a lot of improvements @puerile22 well done 🥇

2022-09-30 14:03 UTC, naseka-mm submitted a review, later dismissed

2022-09-30 15:32 UTC, ikhodas approved these changes
Just work with Roman review advices, after this you can merge, nice job!

2022-09-30 16:33 UTC, puerile22 commented on google_ads_data/account_utils.py
> +def cust_id_to_account(cust_id: str, env: str = "prod") -> dict:
I think `env` is pretty descriptive enough, right? I have not used Enum before but I'll try update this.

2022-10-05 14:08 UTC, mkarbouski approved these changes
I love the progress that we have!

2022-10-06 16:55 UTC, ikhodas approved these changes
Great Job

2022-10-06 18:03 UTC, GermanParra approved these changes

2022-10-14 07:19 UTC, rsen-motivemetrics approved these changes

2022-10-14 16:58 UTC, merged